// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/person.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreatePersonRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePersonRequest) Reset()         { *m = CreatePersonRequest{} }
func (m *CreatePersonRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePersonRequest) ProtoMessage()    {}
func (*CreatePersonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d96e036db946e632, []int{0}
}

func (m *CreatePersonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePersonRequest.Unmarshal(m, b)
}
func (m *CreatePersonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePersonRequest.Marshal(b, m, deterministic)
}
func (m *CreatePersonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePersonRequest.Merge(m, src)
}
func (m *CreatePersonRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePersonRequest.Size(m)
}
func (m *CreatePersonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePersonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePersonRequest proto.InternalMessageInfo

func (m *CreatePersonRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatePersonRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreatePersonRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type SinglePersonRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SinglePersonRequest) Reset()         { *m = SinglePersonRequest{} }
func (m *SinglePersonRequest) String() string { return proto.CompactTextString(m) }
func (*SinglePersonRequest) ProtoMessage()    {}
func (*SinglePersonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d96e036db946e632, []int{1}
}

func (m *SinglePersonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SinglePersonRequest.Unmarshal(m, b)
}
func (m *SinglePersonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SinglePersonRequest.Marshal(b, m, deterministic)
}
func (m *SinglePersonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SinglePersonRequest.Merge(m, src)
}
func (m *SinglePersonRequest) XXX_Size() int {
	return xxx_messageInfo_SinglePersonRequest.Size(m)
}
func (m *SinglePersonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SinglePersonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SinglePersonRequest proto.InternalMessageInfo

func (m *SinglePersonRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdatePersonRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePersonRequest) Reset()         { *m = UpdatePersonRequest{} }
func (m *UpdatePersonRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePersonRequest) ProtoMessage()    {}
func (*UpdatePersonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d96e036db946e632, []int{2}
}

func (m *UpdatePersonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePersonRequest.Unmarshal(m, b)
}
func (m *UpdatePersonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePersonRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePersonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePersonRequest.Merge(m, src)
}
func (m *UpdatePersonRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePersonRequest.Size(m)
}
func (m *UpdatePersonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePersonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePersonRequest proto.InternalMessageInfo

func (m *UpdatePersonRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdatePersonRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdatePersonRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdatePersonRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type PersonProfileResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonProfileResponse) Reset()         { *m = PersonProfileResponse{} }
func (m *PersonProfileResponse) String() string { return proto.CompactTextString(m) }
func (*PersonProfileResponse) ProtoMessage()    {}
func (*PersonProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d96e036db946e632, []int{3}
}

func (m *PersonProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonProfileResponse.Unmarshal(m, b)
}
func (m *PersonProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonProfileResponse.Marshal(b, m, deterministic)
}
func (m *PersonProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonProfileResponse.Merge(m, src)
}
func (m *PersonProfileResponse) XXX_Size() int {
	return xxx_messageInfo_PersonProfileResponse.Size(m)
}
func (m *PersonProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PersonProfileResponse proto.InternalMessageInfo

func (m *PersonProfileResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PersonProfileResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PersonProfileResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PersonProfileResponse) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type SuccessResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuccessResponse) Reset()         { *m = SuccessResponse{} }
func (m *SuccessResponse) String() string { return proto.CompactTextString(m) }
func (*SuccessResponse) ProtoMessage()    {}
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d96e036db946e632, []int{4}
}

func (m *SuccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuccessResponse.Unmarshal(m, b)
}
func (m *SuccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuccessResponse.Marshal(b, m, deterministic)
}
func (m *SuccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuccessResponse.Merge(m, src)
}
func (m *SuccessResponse) XXX_Size() int {
	return xxx_messageInfo_SuccessResponse.Size(m)
}
func (m *SuccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SuccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SuccessResponse proto.InternalMessageInfo

func (m *SuccessResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*CreatePersonRequest)(nil), "personservice.CreatePersonRequest")
	proto.RegisterType((*SinglePersonRequest)(nil), "personservice.SinglePersonRequest")
	proto.RegisterType((*UpdatePersonRequest)(nil), "personservice.UpdatePersonRequest")
	proto.RegisterType((*PersonProfileResponse)(nil), "personservice.PersonProfileResponse")
	proto.RegisterType((*SuccessResponse)(nil), "personservice.SuccessResponse")
}

func init() {
	proto.RegisterFile("proto/person.proto", fileDescriptor_d96e036db946e632)
}

var fileDescriptor_d96e036db946e632 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x65, 0xbb, 0xdd, 0xa2, 0x23, 0x75, 0x21, 0x55, 0x28, 0x3d, 0xc8, 0x52, 0x14, 0xbc, 0xd8,
	0x05, 0xfd, 0x03, 0xf5, 0xb8, 0x48, 0x49, 0xf1, 0xe2, 0x45, 0xba, 0xed, 0x58, 0x03, 0x6d, 0x93,
	0x4d, 0x5a, 0xff, 0xd3, 0x3f, 0x12, 0x93, 0xa5, 0x68, 0x1b, 0xd4, 0x8b, 0xa7, 0xcc, 0x9b, 0x0c,
	0xef, 0xbd, 0xcc, 0x23, 0x40, 0x84, 0xe4, 0x1d, 0x5f, 0x0b, 0x94, 0x8a, 0xb7, 0x89, 0x06, 0xc4,
	0x37, 0x48, 0xa1, 0x7c, 0x63, 0x05, 0xc6, 0x39, 0x04, 0x77, 0x12, 0xf3, 0x0e, 0x53, 0xdd, 0xa6,
	0xb8, 0xeb, 0x51, 0x75, 0x84, 0x80, 0xdb, 0xe6, 0x0d, 0x86, 0xb3, 0xd5, 0xec, 0xf2, 0x90, 0xea,
	0x9a, 0x9c, 0xc0, 0x02, 0x9b, 0x9c, 0xd5, 0xa1, 0xa3, 0x9b, 0x06, 0x90, 0x15, 0x1c, 0x89, 0x57,
	0xde, 0xe2, 0x43, 0xdf, 0x6c, 0x51, 0x86, 0x73, 0x7d, 0xf7, 0xb5, 0x15, 0x5f, 0x40, 0x90, 0xb1,
	0xb6, 0xaa, 0x47, 0x12, 0xc7, 0xe0, 0xb0, 0x52, 0x0b, 0x2c, 0xa8, 0xc3, 0xca, 0x78, 0x07, 0xc1,
	0xa3, 0x28, 0x27, 0x4e, 0x46, 0x63, 0x83, 0x33, 0xc7, 0xe6, 0x6c, 0xfe, 0x83, 0x33, 0x77, 0xea,
	0x4c, 0xc1, 0xa9, 0x11, 0x4b, 0x25, 0x7f, 0x61, 0x35, 0x52, 0x54, 0xe2, 0x73, 0x35, 0xff, 0x2a,
	0x7a, 0x05, 0xcb, 0xac, 0x2f, 0x0a, 0x54, 0x6a, 0x90, 0x8b, 0xe0, 0x40, 0xee, 0xeb, 0xfd, 0xc6,
	0x07, 0x7c, 0xfd, 0xee, 0x80, 0x6f, 0x4c, 0x66, 0x26, 0x32, 0x42, 0xc1, 0x33, 0x91, 0x91, 0x38,
	0xf9, 0x16, 0x66, 0x62, 0x49, 0x32, 0x3a, 0x1f, 0xcd, 0xd8, 0x1f, 0x9c, 0x82, 0x4b, 0x31, 0x2f,
	0x27, 0x8c, 0x96, 0xe0, 0xfe, 0xc8, 0xb8, 0x01, 0xcf, 0xc4, 0x39, 0xe1, 0xb4, 0xa4, 0x1c, 0x9d,
	0x8d, 0x75, 0x47, 0x1b, 0xda, 0x80, 0x77, 0x8f, 0x35, 0x5a, 0xd8, 0x6c, 0x0e, 0x7f, 0x61, 0xbb,
	0x5d, 0x3e, 0xf9, 0x15, 0x7f, 0xae, 0xa4, 0x28, 0xd6, 0xfa, 0x53, 0x6c, 0x3d, 0x7d, 0xdc, 0x7c,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xb7, 0x75, 0x5b, 0x31, 0x03, 0x00, 0x00,
}
